Skillink-org/Zikaron-Laderech

app/components/Button/Button.jsx
1. added default value for disabled.
2. onClick function was inserted incorrectly.
3. change the name from value to children for clarity.
=> fix to button

app/components/ImageWithTitle/ImageWithTitle.js, app/components/ImageWithTitle/ImageWithTitle.module.scss, app/page.jsx
הוספתי את הקומפוננטה Image with title
=> Image with title

app/components/Footer/index.jsx, app/components/Footer/style.module.scss, app/components/Header/NavList.jsx, app/components/Header/Search.jsx, app/components/Header/style.module.scss, app/components/NavLink/index.jsx, app/components/NavLink/style.module.scss, lib/NavigationList.js
- Using map to render NavLinks (stored in lib folder)
- NavLink component to show hover and active links + support for additional props
- small HTML tag replaced to Div tag with copyright class
- Header placeholder input replaced with SearchInput shared component
- menu icon on mobile stay in static position when navigation is closed
=> Nav link component - ZL-11

app/components/ProfileCard/index.jsx, app/components/ProfileCard/style.module.scss
I changed to using Next images, and reduced the size of the card a bit.
=> Using Next-Image, and reduce the size of card.

app/components/ProfileCard/style.module.scss
I changed to using Next images.
=> Profile card

env.md, package-lock.json
1. Installed dotenv package to manage environment variables.
2. Added env.md to provide instructions on creating and using the .env file.
=> Install dotenv and add env.md to explain environment file setup

app/components/AuthPopup/GoogleAuth.jsx, app/components/AuthPopup/index.jsx, app/components/AuthPopup/style.module.scss, app/components/GenericInput/index.jsx, app/components/GenericInput/style.module.scss, app/components/Header/AuthButton.jsx, app/components/Header/UserProfile.jsx, app/components/Header/index.jsx, app/components/Header/style.module.scss, lib/FormFields.js, package.json, pnpm-lock.yaml
קומפוננטות חדשות:
1. תיקיה חדשה במיקום app/components/authPopup
ובה יש:
* קובץ בשם  index ובו הקומפוננטה שמציגה את טופס ההרשמה\התחברות.
(השדות עבור הטפסים נלקחים מדף lib/FormFields.js)
* קומפוננטה app/authPopup/GoogleAuth.jsx
מציגה את הכפתור של התחברות באמצעות גוגל, עם provider שמקבל את הclient_id מה-env.
* קובץ style עבור העיצובים.
2. תיקיה חדשה בשם GenericInput
המכילה דף index ו-style עבור input גנרי לשדות הטופס.
3. לתוך התיקיה Header הוספתי 2 קומפוננטות:
הקומפוננטה AuthButton - כפתור (המשתמש ברכיב כפתור הקיים) ובלחיצה עליו נפתח הפופאפ להתחברות או הרשמה
* הקומפוננטה UserProfile - רכיב המציג את תמונת הפרופיל של המשתמש- אם קיימת, ואת ראשי התיבות של שמו- אם לא קיימת, ובנוסף מציג גם את שמו של המשתמש.
כרגע פיקטיבי.
אשמח להערות כדי שאוכל להתקדם במשימה גם לצד השרת.
תודה!
=> שלב א' של משימת המשתמש בצד הלקוח

app/all-fallen/page.jsx, app/all-fallen/page.module.scss, app/components/Button/style.module.scss, app/components/CustomBubble/style.module.scss, app/components/DynamicBackground/index.jsx, app/components/DynamicBackground/style.module.scss, app/components/HobbyTag/style.module.scss, app/components/NavLink/style.module.scss, app/components/ProfileCard/index.jsx, app/components/ProfileCard/style.module.scss, app/components/SearchInput/index.jsx, app/components/TitleDivider/style.module.scss, package-lock.json, package.json, styles/_mixins.scss, styles/_vars.scss
feat(UI): Improve all-fallen page and fallen card design
- Enhanced layout and styling for the all-fallen page
- Improved visuals and UX for the fallen card component
- Refined spacing and typography
=> UI design improvements

.gitignore, package-lock.json, package.json, server/connect.js
1. Installed mongoose as a dependency
2. Adapted database link construction to use environment variables from .env
3. Enhanced logging for better development process
4. Added documentation for the connectToDB function
=> Install mongoose, adapt DB link to .env, improve logs, and document connectToDB function

app/add-fallen/page.jsx, app/add-fallen/page.module.scss, app/components/ImageWithTitle/index.jsx
The client side is not yet complete.  
I still need to finalize the server request for adding a fallen and set up image upload to Cloudinary.  
@nshahaf  will handle the responsive design.
=> Add fallen page

app/components/Header/index.jsx, app/components/Header/style.module.scss, server/actions/user.action.js
insert auth component into header layout
Search component is visible only for desktop/laptop screen width
=> header layout with auth and search component

app/add-fallen/page.jsx, server/models/fallen.js, server/models/fallen.model.js, server/service/fallen.service.js
- Changed `isAccepted` (Boolean) to `status` (Enum) with values: "pending", "approved", "rejected"
- Updated default value to "pending"
- Adjusted schema and related logic to support new status field
=> Replaced the isAccepted field (boolean) with a new status field (enum)

app/components/Header/MobileNav.jsx, app/components/Header/NavList.jsx, app/components/Header/style.module.scss
1. mobile nav menu now close on navigation
2. prevent layout shift between large and mid screens
=> Mobile nav - Close on navigation

app/admin/page.jsx, app/all-fallen/[fallen]/page.module.scss, app/all-fallen/page.jsx, app/all-fallen/page.module.scss, app/components/DynamicBackground/index.jsx, app/components/FallenForm/index.jsx, app/components/FallenList/FallenList.jsx, app/components/FallenList/style.module.scss, app/components/FallenTable/index.jsx, app/components/FallenTable/style.module.scss, app/components/Header/MobileNav.jsx, app/components/Header/NavList.jsx, app/components/Header/style.module.scss, app/components/HobbyBubble/style.module.scss, app/components/HobbyDataBubble/index.jsx, app/components/HobbyDataBubble/style.module.scss, app/components/HobbyTag/index.jsx, app/components/HobbyTag/style.module.scss, app/components/ProfileCard/style.module.scss, app/components/SearchForm/SearchForm.jsx, app/components/SearchForm/style.module.scss, lib/colors.js
Reverts Skillink-org/Zikaron-Laderech#76
=> Revert "Push back" - auth erros

app/admin/page.jsx, app/components/FallenForm/index.jsx, app/components/FallenTable/index.jsx, app/components/FallenTable/style.module.scss
Reverts Skillink-org/Zikaron-Laderech#72:
errors:
[ Server ] [31m[auth][error][0m MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
=> Revert "Restrict admin page access to admins only and add StatusMessage for fallen approval/rejection feedback"

app/all-fallen/page.jsx, app/all-fallen/page.module.scss, app/components/DynamicBackground/index.jsx, app/components/FallenList/index.jsx, app/components/FallenList/style.module.scss, app/components/HobbyDataBubble/index.jsx, app/components/HobbyTag/index.jsx, app/components/HobbyTag/style.module.scss, app/components/SearchForm/SearchForm.jsx, app/components/SearchForm/style.module.scss, lib/colors.js, server/serverContact.js
This PR restores the changes that were originally introduced in PR #69 , which were merged but later reverted due to conflicts with another merge. After resolving the issues, these changes are now being re-applied safely.
=> re-push PR #69

app/components/GenericInput/index.jsx, app/components/GenericInput/style.module.scss, app/reset-password/[token]/page.jsx, public/eye-off.svg, public/eye.svg
I Added Icons to show and hide password in GenericInput component.
=> Add Icons to show and hide password in GenericInput

app/about/page.jsx, app/about/page.module.scss, app/components/GenericInput/style.module.scss, app/components/InvitationBubble/InvitationBubble.jsx, app/components/LargeBubble/index.jsx
- Created an initial responsive version of the About page.
- Fixed an incorrect import in the `LargeBubble` component.
- Modified `GenericInput`'s styles to align with `Button`'s styles.
=> About page

app/about/page.jsx, server/service/fallen.service.js
- Showing real stats, queried from the db, in `about-page`'s bottom.
=> feat: showing real data in about-page stats

app/add-fallen/page.jsx, server/service/fallen.service.js
- Implemented proper error handling across the application
- Added dedicated error message component (`StatusMessage`) for consistent error display
- Centralized error handling in form submissions
- Added comprehensive duplicate checking mechanism
- Validation includes:
- First and last name matching (case-insensitive)
- Birth date comparison with 48-hour flexibility
- Death date comparison with 48-hour flexibility
- Clear error messages when duplicates are found
- Added automatic email notifications to admin
- Notifications are sent when:
- New fallen profile is submitted
- Contact form is submitted
- `server/service/fallen.service.js`
- `app/add-fallen/page.jsx`
- `lib/email.js`
- `components/StatusMessage/index.jsx`
- Used environment variables for secure email configuration
- …
=> Improve fallen duplicate check: Add birth and death date validation
